services:
  app:
    build:
      context: .
      target: development
    container_name: ${APP_CONTAINER_NAME:-cine-backend-nest}
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3000
      - POSTGRES_HOST=db
      - DATABASE_URL=postgres://${POSTGRES_USER:-nodejs}:${POSTGRES_PASSWORD:-123456}@db:5432/${POSTGRES_DB:-postgres}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cine-network

  db:
    image: postgres:15-alpine
    container_name: ${DB_CONTAINER_NAME:-cine-postgres-db}
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-nodejs}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-123456}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-nodejs} -d ${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cine-network
  sonarqube:
    image: sonarqube:lts-community
    container_name: cine-sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - cine-network

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: cine-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - cine-network    

volumes:
  postgres_data:
    name: cine_postgres_data

  sonarqube_data:
    name: cine_sonarqube_data

  sonarqube_extensions:
    name: cine_sonarqube_extensions

  sonarqube_logs:
    name: cine_sonarqube_logs
    
  jenkins_home:
    name: cine_jenkins_home

networks:
  cine-network:
    name: cine_backend_network
    driver: bridge




